delete(findall(gcf,'type','annotation'))
points=[];
numPixels = nnz(segImg);
Per = numPixels / 25;



annotation('textbox',...
    [0.15 0.74 0.3 0.15],...
    'String', sprintf('Número de pixels = %.0f\n\nPerímetro = %.2f cm',numPixels, Per),...
    'FontSize',14,...
    'FontName','Consolas',...
    'LineStyle','none',...
    'EdgeColor','none',...
    'BackgroundColor',[0.4 0.4 0.4],...
    'Color','w',...
    'FitBoxToText', 'on');
imshow(imfuse(segImg,I,'falsecolor','ColorChannels',[1 2 2]));

set(btn2, 'enable','off');
set(btn3, 'enable','off');
set(btn4, 'enable','off');