clear all;
close all;



fh=figure('WindowButtonDownFcn', 'mouseButton','Menubar','none','Color','white', 'Position', [300 100 900 600], 'Resize', 'off'); 
ax=axes();
set(gca, 'visible', 'off')


points=[];


annotation('textbox','HorizontalAlignment','center','VerticalAlignment', 'middle', ...
'FontSize',25, 'Units','normalized', 'Position',[0 0 1 1], 'string', 'Selecione Imagem','LineStyle','none')



btn5=uicontrol(fh, ...
    'Style', 'pushbutton',...
    'String', '<html><center>Selecionar <br> Imagem',...
    'Position', [20 20 60 40],...
    'Callback', 'Img');

btn1=uicontrol(fh, ...
    'Style', 'pushbutton',...
    'String', 'Reset',...
    'Position', [800 20 60 40],...
    'Callback', 'ButtonRes');


btn2=uicontrol(fh, ...
    'Style', 'pushbutton',...
    'String', 'Recortar',...
    'Position', [90 20 60 40],...
    'Callback', 'ButtonCortar');

btn3=uicontrol(fh, ...
    'Style', 'pushbutton',...
    'String', '<html><Center>Calcular <br> Contorno',...
    'Position', [160 20 60 40],...
    'Callback', 'ButtonSeg');

btn4=uicontrol(fh, ...
    'Style', 'pushbutton',...
    'String', '<html><Center>Calcular <br> Perímetro',...
    'Position', [230 20 60 40],...
    'Callback', 'ButtonCal');


set(btn1, 'enable','off');
set(btn2, 'enable','off');
set(btn3, 'enable','off');
set(btn4, 'enable','off');
